### ISSUE TITLE
Swift SDK requires secret, which is the opposite of what the docs say

### ISSUE THREAD

**Issue by duncsand** [uploadcare/uploadcare-swift#101]
### Describe the bug

The docs for the swift library are very clear that to use the uploadAPI the secret is optional. This is consistent with the underlying API as I can do a cURL command with the secret to upload a file and it works fine. However, when using the Swift SDK I can't do an upload without specifying the secret.

Use the Swift SDK to upload a file without specifying a secret. This results in "Invalid signature. Please check your secret key." response.
If I specific a secret, it works.

### Expected behavior

I should be able to run the above code and not need to specify a secret.

### Code / screenshots

```
var uploadcare: Uploadcare = Uploadcare(withPublicKey: "myPublicKey")
...
profileImage = profileImage.imageResized(to: CGSize(width: 30.0, height: 30.0))
let fileForUploading = uploadcare.file(fromData: profileImage.jpegData(compressionQuality: 0.2)!)
fileForUploading.upload(withName: "random_file_name.jpg", store: .store, { result in
    print(result)
})
```

### Environment

 - Library version: 0.8.1
 - Language/framework version: Swift
 - OS version: Mac OS 12.6

**Comment by makoni** [comment]
Thank you for the report @duncsand 

I found that uploading actually works but for small files callback returns an error.

That bug should be fixed in https://github.com/uploadcare/uploadcare-swift/pull/104

We're gonna merge it and release new version soon.

**Comment by makoni** [comment]
Done in 0.9.0

**Comment by duncsand** [comment]
Excellent. I tested and confirm it's fixed. Nice job!
