### ISSUE TITLE
Crash while trying to upload simple txt file

### ISSUE THREAD

**Issue by rnr** [uploadcare/uploadcare-swift#102]
### Describe the bug

I got crash inside Uploadcare pod while trying to upload little 25-bytes txt file

Use **_uploadcare.uploadAPI.directUpload_** function for this file 

### Expected behavior

No crash for little files 

### Code / screenshots

Crash screenshot:
<img width="1333" alt="Screenshot 2022-09-22 at 15 54 24" src="https://user-images.githubusercontent.com/37253/191767413-ffe5aef9-7898-46d1-bc2f-0bd5bfc415f6.png">

Test file:
[test text file.txt](https://github.com/uploadcare/uploadcare-swift/files/9626492/test.text.file.txt)

### Environment

 - Library version: 0.8.1
 - Language/framework version: Swift 5
 - OS version: iOS 16 (and iOS 15.7 too)

**Comment by rnr** [comment]
Any information on this Crash?

**Comment by makoni** [comment]
Thanks for the report, we've just released a new version 0.8.2, the crash should be fixed now
