### ISSUE TITLE
Upload method enters ".failure" case when uploading larger files

### ISSUE THREAD

**Issue by GlennKeller** [uploadcare/uploadcare-swift#105]
### Describe the bug

Uploading a video file longer than 10 seconds always enters the “.failure" case - even though the file is successfully being uploaded to Uploadcare.

The error message is "unknown"

### Expected behavior

Enter the ".success" case after successfully being uploaded to Uploadcare.

### Code / Screenshot

![Screenshot 2022-11-22 at 14 45 34](https://user-images.githubusercontent.com/11356768/203356813-95c0c7bc-c695-4257-aa03-5aaa86f70a1d.png)

### Environment

 - SDK version: 0.9.0
 - Language/framework version: Swift 5
 - OS version: iOS 16.1.1

**Comment by makoni** [comment]
Hi @GlennKeller 

Thanks for the report. That bug should be fixed now in https://github.com/uploadcare/uploadcare-swift/pull/106 . A new release will be available soon after PR will be reviewed and merged. I'll tag you when it will be published.

**Comment by GlennKeller** [comment]
Thanks @makoni!

**Comment by makoni** [comment]
@GlennKeller new release is ready: https://github.com/uploadcare/uploadcare-swift/releases/tag/0.9.1

Thanks again for the report!
