### ISSUE TITLE
Deprecate PUT /group/{uuid}/storage/

### ISSUE THREAD

**Issue by rsedykh** [uploadcare/uploadcare-swift#124]
It was deprecated.

<img width="868" alt="image" src="https://github.com/uploadcare/uploadcare-php/assets/515987/56a7534d-8b27-42c9-81a7-af10a92315f4">

https://uploadcare.com/api-refs/upload-api/#tag/Groups/operation/filesGroupInfo
https://uploadcare.com/api-refs/rest-api/v0.7.0/#tag/Group/operation/groupInfo

To store or remove files from a group, query the list of files in it, split the list into chunks of 100 files per chunk and then perform batch file storing or batch file removal for all the chunks.

p.s. Don't forget to update uploadcare-php-example if necessary.

**Comment by makoni** [comment]
Marked `datetimeStored` property as deprecated in `Group` and `UploadedFilesGroup` models. Both are optional so even if it will be removed on the API side that won't break even apps using old version of the lib.
