### ISSUE TITLE
Error code 400 on Multipart uploads

### ISSUE THREAD

**Issue by mato2593** [uploadcare/uploadcare-swift#65]
### Describe the bug

When I try to upload a file using the multipart upload, I get an error with status code 400, but when I upload exactly the same file using the direct upload, it works.

### Expected behavior

I want to be able to upload a file using a Multipart request

### Code / screenshots

```swift
    guard
      let uploadcare = uploadcare,
      let imageData = image.jpegData(compressionQuality: 0.5)
    else {
      onError(nil)
      return
    }
    
    // THIS WORKS
    uploadcare.uploadAPI.upload(
      files: ["image.jpg": imageData],
      store: .doNotStore,
      { progress in
        progressCallback?(progress)
      }, 
      { (files, error) in
        if let error = error {
          onError(error)
          return
        }
        
        guard let files = files, let uploadedFile = files.first?.value else {
          onError(nil)
          return
        }
        
        onSuccess(uploadedFile)
      }
    )
    
    // THIS GETS A 400 ERROR
    // As a side note, this doesn't work if I define fileToUpload here as let fileToUpload = ...
    // This is because self is nil in the completion closure inside UploadedFile.upload, so I had to
    // keep a reference to the file
    fileToUpload = uploadcare.uploadAPI.file(fromData: imageData)
    fileToUpload?.upload(
      withName: "image.jpg",
      store: .doNotStore,
      { progress in
        progressCallback?(progress)
      },
      { (file, error) in
        if let file = file {
          onSuccess(file)
        } else {
          onError(error)
        }
      }
    )
```

### Environment

 - Library version: 1.0.0
 - Language/framework version: Swift 5
 - OS version: iOS 13

**Comment by makoni** [comment]
@mato2593 we just released new version of SDK 0.1.0-RC. Please try new version and let us know  how it works

**Comment by mato2593** [comment]
@makoni I'm using Cocoapods to install the library. Do I need to point to develop to get that version?

**Comment by makoni** [comment]
Looks like we had incorrect podspec file in the repo. Updated it to correct values.

Try again. No need to set develop branch:
`pod 'Uploadcare', git: 'https://github.com/uploadcare/uploadcare-swift'`

Version now should be 0.1.0-RC
