### ISSUE TITLE
Completion block stops working after several uploads.

### ISSUE THREAD

**Issue by tikhop** [uploadcare/uploadcare-swift#74]
### Describe the bug

If you try to initialize (maybe just upload a picture) several time Uploadcare instance, then completion block stops working.

- Create a viewcontroller and initilize `Uploadcare`:
`let uploadcare = Uploadcare(withPublicKey: "PK", secretKey: "SK")`

- Select an image from photo library and try to upload it:
```
let uuid = UUID().uuidString
uploadcare.uploadAPI.upload(files: [uuid: data], store: .store) { [weak self] (progress) in
	//update progress bar
} _: { [weak self] (dict, error) in
       // Called only once, if you close current view controller and open it again and initialize `Uploadcare` one more time,
       // then it will never get called again. `NSURLSessionDelegate` must be the current `UploadAPI` object, but it's not 
}
```

### Environment

 - Library version: 0.3.0
 - OS version: ios 14

**Comment by makoni** [comment]
@tikhop there's new commit on develop branch with fix for that. Please try to add the lib develop branch and tell us if it works now

**Comment by tikhop** [comment]
thanks, I will check it out later today.

**Comment by tikhop** [comment]
Hi @makoni, sorry for the late response. I've tried dev branch and it works well, seems like the issues had been fixed. I think we can close it. Thank you!
