### ISSUE TITLE
Request timed out

### ISSUE THREAD

**Issue by paulsizer** [uploadcare/uploadcare-swift#92]
Hi, I am trying to run the iOS Demo app and when selecting a 98.1MB video from the files option I receive the following error:

<67582B98-8EC6-4697-9669-B8E3A1C5794A>.<20> finished with error [-1001] Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={_kCFStreamErrorCodeKey=-2102, NSUnderlyingError=0x2802d2ca0 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <67582B98-8EC6-4697-9669-B8E3A1C5794A>.<20>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <67582B98-8EC6-4697-9669-B8E3A1C5794A>.<20>"
), NSLocalizedDescription=The request timed out., NSErrorFailingURLStringKey=<URL>, _kCFStreamErrorDomainKey=4}
UploadAPI.swift:576 -> uploadIndividualFilePart(_:toPresignedUrl:withMimeType:task:group:completeMessage:onComplete:): The request timed out.

**Comment by paulsizer** [comment]
Any information on this one?

**Comment by paulsizer** [comment]
Any information on this one?

**Comment by makoni** [comment]
@paulsizer latest testing works on my side 🤔 Is that still an issue? Probably there was some service issues. If it still doesn't work - is it possible that there're some network restrictions on your side?
