### ISSUE TITLE
Completion blocks don't get called

### ISSUE THREAD

**Issue by shakked** [uploadcare/uploadcare-swift#95]
### Describe the bug

The completion blocks for upload operations are not getting called, but the files are uploading successfully.

Use this code:
```
let uploadcare = Uploadcare(withPublicKey: "PUBLIC_KEY", secretKey: "SECRET_KEY")
        
        guard let url = URL(string: "https://source.unsplash.com/random") else { return }
        guard let data = try? Data(contentsOf: url) else { return }

        // You can create UploadedFile object to operate with it
        let fileForUploading1 = uploadcare.file(fromData: data)
     
        // Handle error or result
        self.task = fileForUploading1.upload(withName: "random_file_name.jpg", store: .store) { (result, error) in
            print(result)
            print(error)
        }
```
### Expected behavior
Completion block should be called after the operation is done.

### Environment

 - Library version: 0.8.0
 - Language/framework version: Swift
 - OS version: iOS 15.5

**Comment by makoni** [comment]
Tried that code in our Demo app and callback gets called every time. Also our integration tests also gets callback called.

Are you sure that fileForUploading1 (which is UploadedFile object) doesn't get deallocated at some moment?

Here's the code I used and tried on iPhone running iOS 15.6 (just added it to SceneDelegate):
```swift
//
//  SceneDelegate.swift
//  Demo
//
//  Created by Sergey Armodin on 26.03.2020.
//  Copyright © 2020 Uploadcare, Inc. All rights reserved.
//

import UIKit
import SwiftUI
import Uploadcare

#warning("Set your public key here if need")
let publicKey = "demopublickey"
let secretKey = "demopublickey"

class SceneDelegate: UIResponder, UIWindowSceneDelegate {

    var window: UIWindow?
    var task: UploadTaskable?

    func scene(_ scene: UIScene, willConnectTo session: UISceneSession, options connectionOptions: UIScene.ConnectionOptions) {
        // Use this method to optionally configure and attach the UIWindow `window` to the provided UIWindowScene `scene`.
        // If using a storyboard, the `window` property will automatically be initialized and attached to the scene.
        // This delegate does not imply the connecting scene or session are new (see `application:configurationForConnectingSceneSession` instead).

        // Create the SwiftUI view that provides the window contents.
        let contentView = MainView()

        // Use a UIHostingController as window root view controller.
        if let windowScene = scene as? UIWindowScene {
            let window = UIWindow(windowScene: windowScene)

            let uploadcare = Uploadcare(
                withPublicKey: publicKey,
                secretKey: secretKey
            )

            let apiStore = APIStore(uploadcare: uploadcare)

            window.rootViewController = UIHostingController(
                rootView: contentView
                    .environmentObject(apiStore)
            )
            self.window = window
            window.makeKeyAndVisible()

            let url = URL(string: "https://source.unsplash.com/random")!
            let data = try! Data(contentsOf: url)

            // You can create UploadedFile object to operate with it
            let fileForUploading1 = uploadcare.file(fromData: data)

            // Handle error or result
            self.task = fileForUploading1.upload(withName: "random_file_name.jpg", store: .doNotStore) { result, error in
                DLog(result as Any)
                DLog(error as Any)
            }
        }
    }

    func sceneDidDisconnect(_ scene: UIScene) {}

    func sceneDidBecomeActive(_ scene: UIScene) {}

    func sceneWillResignActive(_ scene: UIScene) {}

    func sceneWillEnterForeground(_ scene: UIScene) {}

    func sceneDidEnterBackground(_ scene: UIScene) {}
}
```
By the way with latest version of the lib you can switch to methods that returns Result type in callbacks:
```swift
// Handle error or result
self.task = fileForUploading1.upload(withName: "random_file_name", store: .doNotStore) { progress in
       print(progress)
} _: { result in
     switch result {
        case .success(let file):
            print(file)
        case .failure(let error):
            print(error.localizedDescription)
        }
}
```

**Comment by shakked** [comment]
I tried your code **exactly** in my project and had the same problems, with no completion blocks being called. I added breakpoints, logs, and even fatalErrors inside of it and nothing was ever triggered. 

Then, I tried removing the package and switching to Cocoapods instead of SPM and it still didn't work. 

However, I did figure it out! It's not the task that was being deallocated or has to be an instance variable, it's the Uploadcare instance:

`let uploadCare: Uploadcare = Uploadcare(withPublicKey: "X", secretKey: "X")` - this should be an instance variable on a class that won't get deallocated. 

Also, I would point out that your docs are wrong on your website and do not work:
(https://uploadcare.com/docs/integrations/swift/) 

The format like so:
```
let fileForUploading1 = uploadcare.uploadAPI.file(fromData: data)
let fileForUploading2 = uploadcare.uploadAPI.file(withContentsOf: url)
```
doesn't work with your latest SDK on SPM or Cocapods. I'd recommend going through all of those docs are verifying the sample code works, and clarifying how important it is to declare that `Uploadcare` variable as an instance variable that won't get deallocated as instantiating it inside of a function will lead to it being deallocated when the completion blocks would be called on classes.

Further, why is the SDK even set up like this? It should be a singleton, or a static func that ensure there won't be a deallocation problem, like each of the following services:
```
Intercom.setApiKey("X", forAppId: "X") // Intercom.com
Mixpanel.initialize(token: "X") // Mixpanel.com
Paywall.configure(apiKey: "X") // Superwall.com
Purchases.configure(withAPIKey: "X", appUserID: "X") // RevenueCat.com
```

Thanks for the help.

- Zach

**Comment by makoni** [comment]
Thank you for feedback. 

> this should be an instance variable on a class that won't get deallocated.

I'll update README with an example using Uploadcare object as a class property

> Also, I would point out that your docs are wrong on your website and do not work:

Thanks, our manager will update it shortly. Latest docs are always in this repo in [Documentation](https://github.com/uploadcare/uploadcare-swift/tree/master/Documentation) if you need it.

> Further, why is the SDK even set up like this? It should be a singleton, or a static func that ensure there won't be a deallocation problem, like each of the following services:

These services from your list are designed to be one project per app while Uploadcare allows you to have multiple projects. So with that SDK it's possible to create an instance for each project and work with them at the same time. Thanks again for your feedback, I'll update README and docs in the repo with some details about it 👍
