### ISSUE TITLE
Store Option Does Not Work

### ISSUE THREAD

**Issue by shakked** [uploadcare/uploadcare-swift#97]
### Describe the bug

When you upload a file with the `.store` behavior, it will not be marked as stored in the dashboard.

1) Upload a file with the .store behavior
2) Notice in the dashboard that it is not stored
### Expected behavior
It should be stored.

### Code / screenshots
<img width="825" alt="Screen Shot 2022-08-15 at 11 45 02 AM" src="https://user-images.githubusercontent.com/5383089/184668394-fddae388-55d7-47ce-b24c-3a29acef8aff.png">
<img width="1743" alt="Screen Shot 2022-08-15 at 11 45 19 AM" src="https://user-images.githubusercontent.com/5383089/184668511-6d110dd6-ca02-464f-a000-19ba650572c0.png">

```
class Upload {
    
    static let shared: Upload = Upload()
    private let uploadCare: Uploadcare = Uploadcare(withPublicKey: "X", secretKey: "X")
    var task: UploadTaskable?
    
    func upload(image: UIImage, failed: @escaping (FGError) -> (), succeeded: @escaping (URL) -> ()) {
        let data = image.pngData()!
        let file = uploadCare.file(fromData: data)
        let name = UUID().uuidString
        task = file.upload(withName: name, store: .store, uploadSignature: nil) { progress in
            
        } _: { (result: Result<UploadedFile, UploadError>) in
            switch result {
            case .failure(let error):
                failed(FGError.generic("Problem Uploading", error.localizedDescription))
            case .success(let file):
                break
            }
        }
    }
}
```

### Environment

 - Library version: 0.8.0
 - Language/framework version: Swift
 - OS version: 15.5

**Comment by makoni** [comment]
Thanks for the report @shakked . The issue should be fixed now in https://github.com/uploadcare/uploadcare-swift/pull/98 and new release will be published after PR review. You can use develop branch for now in case of urgency.

**Comment by makoni** [comment]
0.8.1 is published: https://github.com/uploadcare/uploadcare-swift/releases/tag/0.8.1
