### ISSUE TITLE
Add file metadata feature from REST API 0.7

### ISSUE THREAD

**Issue by rsedykh** [uploadcare/uploadcare-swift#99]
* Add `metadata[{key}]` to Upload API methods (direct, multipart, url)
* All new [metadata methods](https://uploadcare.com/api-refs/rest-api/v0.7.0/#tag/File-metadata) from the new REST API version

It requires REST API 0.7, so probably should also update `/files/{uuid}/`, `/files/`, `/group/{uuid}/` and `/group/{uuid}/storage/` along the way (see [changelog](https://uploadcare.com/api-refs/rest-api/v0.7.0/#tag/Changelog)).

**Comment by makoni** [comment]
Implemented in https://github.com/uploadcare/uploadcare-swift/pull/104
